#pragma once

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define PIMORONI_TRACKBALL_SCALE 5

#define VIAL_KEYBOARD_UID {0xA4, 0x49, 0x1D, 0x5E, 0xF2, 0x7B, 0x90, 0x13}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}
